apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: banking-ingress
  namespace: argocd
  labels:
    app.kubernetes.io/name: banking-ingress
    app.kubernetes.io/part-of: banking-platform
spec:
  project: workloads-project
  source:
    repoURL: https://github.com/ManoharBarma/k8s-platform-lab.git
    targetRevision: HEAD
    path: workloads/ingress
  destination:
    server: https://kubernetes.default.svc
    namespace: banking-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
