apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: banking-microservices
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/ManoharBarma/k8s-platform-lab.git
        revision: HEAD
        directories:
          - path: workloads/banking-apps/*
  template:
    metadata:
      name: '{{.path.basename}}'
    spec:
      project: workloads-project
      sources:
        - repoURL: ghcr.io/manoharbarma
          chart: banking-app-standard-template
          targetRevision: 1.0.0
          helm:
            valueFiles:
              - $values/{{.path.path}}/values.yaml
        - repoURL: https://github.com/ManoharBarma/k8s-platform-lab.git
          targetRevision: HEAD
          ref: values
      destination:
        server: https://kubernetes.default.svc
        namespace: banking-app
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - ServerSideApply=true
