apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookinfo
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/name: bookinfo
    app.kubernetes.io/part-of: k8s-platform-lab
spec:
  project: workloads-project
  source:
    repoURL: https://github.com/ManoharBarma/k8s-platform-lab.git
    targetRevision: HEAD
    path: workloads/bookinfo
  destination:
    server: https://kubernetes.default.svc
    namespace: bookinfo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
