apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istiod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/name: istiod
    app.kubernetes.io/part-of: k8s-platform-lab
spec:
  project: platform-project
  sources:
    - repoURL: https://blob.istio.io/istio-release/charts
      targetRevision: 1.31.0
      chart: istiod
      helm:
        releaseName: istiod
        valueFiles:
          - $values/platform/values/istiod.yaml
    - repoURL: https://github.com/ManoharBarma/k8s-platform-lab.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
