apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
  labels:
    app.kubernetes.io/name: metrics-server
    app.kubernetes.io/part-of: k8s-platform-lab
spec:
  project: platform-project
  source:
    repoURL: https://kubernetes-sigs.github.io/metrics-server/
    chart: metrics-server
    targetRevision: 3.13.0
    helm:
      releaseName: metrics-server
      values: |
        args:
          - --kubelet-insecure-tls
          - --kubelet-preferred-address-types=InternalIP,Hostname
  destination:
    server: https://kubernetes.default.svc
    namespace: metrics-server
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
