adminPassword: admin
persistence:
  enabled: false
grafana.ini:
  server:
    root_url: /grafana/
    serve_from_sub_path: true
  auth.anonymous:
    enabled: true
    org_role: Admin
ingress:
  enabled: true
  ingressClassName: nginx
  path: /grafana
  pathType: Prefix
  hosts: []
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-server.monitoring.svc.cluster.local/prometheus
        access: proxy
        isDefault: true
      - name: Loki
        type: loki
        url: http://loki.monitoring.svc.cluster.local:3100
        access: proxy
        isDefault: false

# Enable sidecar to load dashboards from ConfigMaps
sidecar:
  dashboards:
    enabled: true
    label: grafana_dashboard
    folder: /tmp/dashboards
    searchNamespace: monitoring
