apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ztunnel
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/name: ztunnel
    app.kubernetes.io/part-of: k8s-platform-lab
spec:
  project: platform-project
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.30.4
    chart: ztunnel
    helm:
      releaseName: ztunnel
      valuesObject:
        profile: ambient
        env:
          L7_MODE: "false"
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
