apiVersion: v1
kind: Namespace
metadata:
  name: ambient-demo
  labels:
    # Enrolls all pods in this namespace into the Istio Ambient mesh data plane
    istio.io/dataplane-mode: ambient
    app.kubernetes.io/name: ambient-demo
    app.kubernetes.io/part-of: k8s-platform-lab
