apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: backend-authz
  namespace: ambient-demo
  labels:
    app.kubernetes.io/name: backend-authz
    app.kubernetes.io/part-of: ambient-demo
spec:
  selector:
    matchLabels:
      app: backend
  action: ALLOW
  rules:
    - to:
        - operation:
            ports: ["80"]
