apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: bookinfo-authz
  namespace: bookinfo
  labels:
    app.kubernetes.io/name: bookinfo-authz
    app.kubernetes.io/part-of: bookinfo
spec:
  action: ALLOW
  rules:
    - to:
        - operation:
            ports: ["80"]
